# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  reuse:
    image: fsfe/reuse:3.0.1@sha256:f8f4851e199f44a0e827ea7d248228e2045e26750707e4f5f1b5875caf4ac51a
    commands:
      - reuse lint
  npm-ci:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - npm ci
  prettier:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - npx prettier . --check
    depends_on:
      - npm-ci
  eslint:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - npx eslint .
    depends_on:
      - npm-ci
  tsc:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - npx tsc
    depends_on:
      - npm-ci
  build:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - npm run build
    depends_on:
      - npm-ci
  vitest:
    image: node:21.6.2-bookworm@sha256:37fdb3efbe0c9e6d64d26e69725e63ff9f92bd0ce1b51763cc46e270b7572620
    commands:
      - apt-get update
      - apt-get install -y firefox-esr
      - npx vitest
    depends_on:
      - build
  deploy:
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1.0.0@sha256:8af4ca908e27d32fcb7e51c1af3544d044bbde5e11a31abbb78363f63172a187
    settings:
      folder: dist
      git_config_name: Kamila Borowska
      git_config_email: kamila@borowska.pw
      ssh_key:
        from_secret: ssh_key
    when:
      - event: push
        branch:
          - master
    depends_on:
      - prettier
      - eslint
      - tsc
      - vitest
