# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  reuse:
    image: fsfe/reuse:2.1.0@sha256:888418362aa2a8ebea12d8dbfb41fa8eeabd0c423f42df7e3968af4cbb8d2ef1
    commands:
      - reuse lint
  build:
    image: node:21.5.0@sha256:b632a1ec41a0927d19a432c525641b9a4451251d0b0b63f1d764810a562ea4e1
    commands:
      - npm ci
      - npx prettier . --check
      - npx eslint .
      - npx tsc --noEmit
      - npm run build
  deploy:
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1.0.0@sha256:8af4ca908e27d32fcb7e51c1af3544d044bbde5e11a31abbb78363f63172a187
    settings:
      folder: dist
      git_config_name: Kamila Borowska
      git_config_email: kamila@borowska.pw
      ssh_key:
        from_secret: ssh_key
    when:
      - event: push
        branch:
          - master
