# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  reuse:
    image: fsfe/reuse:2.1.0@sha256:888418362aa2a8ebea12d8dbfb41fa8eeabd0c423f42df7e3968af4cbb8d2ef1
    commands:
      - reuse lint
  build:
    image: node:21.5.0@sha256:b632a1ec41a0927d19a432c525641b9a4451251d0b0b63f1d764810a562ea4e1
    commands:
      - npm ci
      - npx prettier . --check
      - npx eslint .
      - npx tsc --noEmit
      - npm run build
  deploy:
    image: bitnami/git:2.43.0@sha256:a8e11f1fdcb57ef7b2ab12995bb28b9060e7dbffa17f75136f523e92f6f270e0
    commands:
      - mkdir ~/.ssh
      - echo codeberg.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIVIC02vnjFyL+I4RHfvIGNtOgJMe769VTF1VR4EB3ZB > ~/.ssh/known_hosts
      - echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - git config --global user.name "Kamila Borowska"
      - git config --global user.email kamila@borowska.pw
      - git clone --single-branch --branch pages git@codeberg.org:$CI_REPO.git pages
      - cd pages
      - cp -ar ../dist/. .
      - git add .
      - git commit -m "Deploying from $CI_COMMIT_SHA" || true
      - git push
    secrets:
      - deploy_key
    when:
      - event: push
        branch:
          - master
