# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  reuse:
    image: fsfe/reuse:2.1.0@sha256:888418362aa2a8ebea12d8dbfb41fa8eeabd0c423f42df7e3968af4cbb8d2ef1
    commands:
      - reuse lint
  build:
    image: node:21.5.0@sha256:b632a1ec41a0927d19a432c525641b9a4451251d0b0b63f1d764810a562ea4e1
    commands:
      - npm ci
      - npx prettier . --check
      - npx eslint .
      - npx tsc --noEmit
      - npm run build
  deploy:
    image: kamilaborowska/plugin-codeberg-pages-deploy:0.1.2@sha256:27b9eaf9154883faaa5e08b78a09a45ab0e2de2bb0f4306e9ff4a0abd8600121
    settings:
      folder: dist
      git_config_name: Kamila Borowska
      git_config_email: kamila@borowska.pw
    secrets:
      - plugin_ssh_key
    when:
      - event: push
        branch:
          - master
